import argparse
import re
import pandas as pd

def get_commandline_args():

    description = ('reads table of Lebedev coordinates and weights from a csv '
                   'file generated by `get_lebedev_table_from_burkardt.py '
                   'and then writes corresponding C++ code in my own style')
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('--table_filename',
                        help='filename of Lebedev quadrature table')

    args = parser.parse_args()

    return args.table_filename



def main():

    table_filename = get_commandline_args()
    print(table_filename)



if __name__ == '__main__':

    main()
